Vagrant.configure("2") do |config|
  config.vm.box = "dietpi"
  config.vm.box_check_update = true

  config.vm.network "forwarded_port", guest: 80, host: 8000

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "install.sh"
end
